#!/bin/bash

dir=$(dirname $0)
. ${dir}/echoex.sh

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
  echoex -green "Path:     " -r $0 -n
  echoex -green "Descript: " -r "change the size of extern screen to 1024x768" -n
  echoex -green Usage: -r -n
  echo "  $(basename $0)"
  exit 0
fi

xrandr --newmode "1280x1024_60.00"  109.00  1280 1368 1496 1712  1024 1027 1034 1063 -hsync +vsync
xrandr --addmode VGA1 "1280x1024_60.00"
xrandr --output VGA1 --mode 1280x1024_60.00 --right-of LVDS1 2>/dev/null
