#!/bin/bash

dir=$(dirname $0)
. ${dir}/echoex.sh

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
  echoex -green "Path:     " -r $0 -n
  echoex -green "Descript: " -r "change the size of extern screen to 1024x768" -n
  echoex -green Usage: -r -n
  echo "  $(basename $0)"
  exit 0
fi

test_VGA1=$(xrandr | grep 'VGA1 disconnected')
test_1280x1024=$(xrandr | grep '1280x1024_60.00')
if [ -z "$test_VGA1" ]; then
  echo VGA connected, changing display mode
  if [ -z "$test_1280x1024" ]; then
    echo add mode 1280x1024_60.00
    xrandr --newmode "1280x1024_60.00"  109.00  1280 1368 1496 1712  1024 1027 1034 1063 -hsync +vsync
    xrandr --addmode VGA1 "1280x1024_60.00"
  fi
  xrandr --output LVDS1 --mode 1366x768 --output VGA1 --mode 1280x1024_60.00 --right-of LVDS1
  echo display mode changed
else
  echo VGA not connected, please connect another screen first
fi

