#!/bin/bash

dir=$(dirname $0)
. echoex.sh

if [[ "$1" == "--help" || "$1" == "-h" || "$1" == "" ]]; then
  echoex -green "Path:     " -r $0 -n
  echoex -green "Descript: " -r "Edit file encrypted by gpg and encrypt again after edit." -n
  echoex -green Usage: -r -n
  echo "  $(basename $0) file-name"
  exit 0
fi

GPGID_FILE=$HOME/myscript/gpg.id
GPGID=`cat $GPGID_FILE`
FILE=$1
ORIGIN_FILE=${FILE}_origin
TMP_FILE=${FILE}_tmp


set -e
set -u
# Uncomment below to show running commnad
#set -x

if [[ "$GPGID" == "" ]]; then
  echo "Please write the id of gpg in file $GPGID_FILE"
  exit -1
fi

if [[ -f $FILE ]]; then
  base64 -d $FILE > $TMP_FILE \
    && gpg --yes --output $ORIGIN_FILE --decrypt $TMP_FILE \
    || gpg --yes --output $ORIGIN_FILE --decrypt $FILE \
    || cp $FILE $ORIGIN_FILE
fi
vim -i NONE -N -u NONE -c "set noundofile nobackup nu ruler showcmd incsearch hlsearch autoindent confirm viminfo= fileencodings=utf-8,gbk,ucs-bom,cp936 display=lastline laststatus=2 backspace=indent,eol,start" \
  -c "nnoremap j gj" \
  -c "nnoremap k gk" \
  -c "nnoremap ; :" \
  -c "nnoremap <space> 3<C-D>" \
  -c "nnoremap <Tab> <C-w>w" \
  -c "nmap <F6> :nohls" \
  -c "vmap <C-c> \"+y<esc>" \
  -c "inoremap <C-v> <esc>:set paste<cr>mua<C-R>+<esc>mv'uv'v=:set nopaste<cr>" \
  $ORIGIN_FILE
gpg --yes --recipient $GPGID --output $TMP_FILE --cipher-algo AES256 --encrypt $ORIGIN_FILE
base64 $TMP_FILE > $FILE
rm $ORIGIN_FILE $TMP_FILE

